import 'dart:async';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mm_pos/data/local/database.dart';
import 'package:mm_pos/features/account/account_providers.dart';
import 'package:mm_pos/features/cash/cash_session_repository.dart';
import 'package:mm_pos/features/expenses/expense_repository.dart';
import 'package:mm_pos/features/expenses/recurring_expense_repository.dart';
import 'package:mm_pos/features/staff/staff_providers.dart';

/// Regression coverage for the audit's Medium tier:
/// - QA-M1 recurring-expense auto-generate duplicates across devices
/// - QA-M4 cash register double-open guard
/// - QA-M6 back-dated expense must still reduce the drawer
/// - QA-M5 owner gates fail closed while the role stream resolves

void main() {
  group('QA-M1: deterministic auto-expense id', () {
    late AppDatabase db;
    late RecurringExpenseRepository repo;
    late ExpenseRepository expenseRepo;

    setUp(() {
      db = AppDatabase.forTesting(NativeDatabase.memory());
      expenseRepo = ExpenseRepository(db, 'shop-1');
      repo = RecurringExpenseRepository(db, 'shop-1', expenseRepo);
    });
    tearDown(() async => db.close());

    test('regenerating a period without the local stamp converges on ONE '
        'expense row', () async {
      final now = DateTime(2026, 8, 5);
      final templateId = await repo.upsertTemplate(
        category: 'rent',
        amount: 150000,
        autoGenerate: true,
        now: now,
      );
      // Enabling mid-month stamps the CURRENT period as done (the
      // justEnabled catch-up guard) — pretend August was never generated by
      // rewinding the stamp to July, like a device that last opened the app
      // in July.
      await (db.update(db.recurringExpenses)
            ..where((t) => t.id.equals(templateId)))
          .write(const RecurringExpensesCompanion(
        lastGeneratedPeriod: Value('2026-07'),
      ));

      final first = await repo.generateDueExpenses(now: now);
      expect(first, hasLength(1));

      // Simulate a second device that generated the same period offline and
      // whose template copy (pre-sync) still says "not generated yet".
      await (db.update(db.recurringExpenses)
            ..where((t) => t.id.equals(templateId)))
          .write(const RecurringExpensesCompanion(
        lastGeneratedPeriod: Value(null),
      ));

      final second = await repo.generateDueExpenses(now: now);
      expect(second, hasLength(1),
          reason: 'the other device fires too — but its rows must converge');

      final expenses = await db.select(db.expenses).get();
      expect(expenses, hasLength(1),
          reason: 'same deterministic id → upsert, not duplicate');
      expect(expenses.single.id, 'auto-$templateId-2026-08');
    });
  });

  group('QA-M4: single open cash session per shop', () {
    late AppDatabase db;
    late CashSessionRepository repo;

    setUp(() {
      db = AppDatabase.forTesting(NativeDatabase.memory());
      repo = CashSessionRepository(db, 'shop-1');
    });
    tearDown(() async => db.close());

    test('openSession refuses while another session is open, works after '
        'close', () async {
      final first = await repo.openSession(openingAmount: 10000);
      await expectLater(
        repo.openSession(openingAmount: 20000),
        throwsA(isA<StateError>().having(
          (e) => e.message,
          'message',
          contains('session_already_open'),
        )),
      );

      // Only one session exists despite the refused attempt.
      expect(await repo.watchSessions().first, hasLength(1));

      await repo.closeSession(first, closingAmount: 10000);
      final second = await repo.openSession(openingAmount: 20000);
      expect(second, isNot(first));
    });
  });

  group('QA-M6: drawer folds expenses by when they were recorded', () {
    late AppDatabase db;
    late CashSessionRepository repo;

    setUp(() {
      db = AppDatabase.forTesting(NativeDatabase.memory());
      repo = CashSessionRepository(db, 'shop-1');
    });
    tearDown(() async => db.close());

    test('an expense recorded during the session but back-dated before it '
        'still reduces expected cash', () async {
      final openedAt = DateTime.now();
      await repo.openSession(openingAmount: 50000);

      await db.into(db.expenses).insert(ExpensesCompanion.insert(
            id: 'backdated',
            shopId: 'shop-1',
            category: 'utilities',
            amount: 3000,
            date: openedAt.subtract(const Duration(days: 1)),
            createdAt: Value(openedAt.add(const Duration(minutes: 5))),
          ));

      final session = await repo.watchCurrentSession().first;
      final report = await repo.reportFor(session!);
      expect(report.expectedCash, 47000,
          reason: 'the money physically left the till during this session');
      expect(report.expensesTotal, 3000);
    });

    test('an expense recorded before the session opened stays out of it, '
        'even if dated inside the window', () async {
      final openedAt = DateTime.now();
      await db.into(db.expenses).insert(ExpensesCompanion.insert(
            id: 'predated',
            shopId: 'shop-1',
            category: 'other',
            amount: 9000,
            date: openedAt.add(const Duration(hours: 1)),
            createdAt: Value(openedAt.subtract(const Duration(hours: 2))),
          ));
      await repo.openSession(openingAmount: 50000);

      final session = await repo.watchCurrentSession().first;
      final expected = await repo.expectedCash(session!);
      expect(expected, 50000,
          reason: 'that cash left during the PREVIOUS session');
    });
  });

  group('QA-M5: owner gate fails closed while the role stream resolves', () {
    test('unresolved local role is NOT owner, even though effectiveRole '
        'would say owner', () async {
      final container = ProviderContainer(overrides: [
        backendAccountRoleProvider.overrideWith((ref) => null),
        staffRoleProvider.overrideWith((ref) =>
            Stream<String>.fromFuture(Completer<String>().future)), // never
      ]);
      addTearDown(container.dispose);

      expect(container.read(isEffectiveOwnerProvider), isTrue,
          reason: 'ordinary UI defaults to owner while loading (unchanged)');
      expect(container.read(isResolvedOwnerProvider), isFalse,
          reason: 'security gates must NOT trust the unresolved default');
    });

    test('resolves true only after the stream reports owner', () async {
      final container = ProviderContainer(overrides: [
        backendAccountRoleProvider.overrideWith((ref) => null),
        staffRoleProvider.overrideWith((ref) => Stream.value('owner')),
      ]);
      addTearDown(container.dispose);

      expect(container.read(isResolvedOwnerProvider), isFalse);
      await Future<void>.delayed(Duration.zero);
      expect(container.read(isResolvedOwnerProvider), isTrue);
    });

    test('invited email staff are never owner, whatever the local switch',
        () async {
      final container = ProviderContainer(overrides: [
        backendAccountRoleProvider.overrideWith((ref) => 'staff'),
        staffRoleProvider.overrideWith((ref) => Stream.value('owner')),
      ]);
      addTearDown(container.dispose);

      await Future<void>.delayed(Duration.zero);
      expect(container.read(isResolvedOwnerProvider), isFalse);
    });
  });
}
