import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/env.dart';
import '../../core/providers.dart';
import '../../data/local/database.dart';
import '../../data/local/shop_data_transition_service.dart';
import '../printing/printing_providers.dart';
import 'license_model.dart';
import 'license_repository.dart';
import 'license_status.dart';
import 'offline_license.dart';

final licenseRepositoryProvider = Provider<LicenseRepository>((ref) {
  return LicenseRepository(ref.watch(settingsRepositoryProvider));
});

/// Pure decision logic for [LicenseController.refreshOnline]'s
/// network-failure fallback: given a license already offline-verified via
/// [OfflineLicense.verify] and the one currently cached, decides whether/how
/// far to extend trust. Deliberately keeps [current]'s own identity
/// (`key`/`shopId`/`plan`) — the offline token only proves the shop is
/// still valid, it isn't a replacement license — so a later successful
/// online re-verify still runs normally rather than this fallback silently
/// pinning the shop to offline-only forever. Returns null if the fallback
/// token is itself expired (nothing to extend with).
CachedLicense? applyOfflineFallback({
  required CachedLicense current,
  required CachedLicense verifiedFallback,
  required DateTime now,
}) {
  if (!verifiedFallback.expiresAt.isAfter(now)) return null;
  return current.copyWith(
    lastVerifiedAt: now,
    expiresAt: verifiedFallback.expiresAt.isAfter(current.expiresAt)
        ? verifiedFallback.expiresAt
        : current.expiresAt,
  );
}

/// The shop's device slots. Re-fetch with `ref.invalidate` after adding or
/// releasing a device (no realtime/stream backing this — it's a plain
/// on-demand read of the `licenses` table).
final shopDevicesProvider = FutureProvider.autoDispose<List<ShopDevice>>((ref) {
  return ref.watch(licenseRepositoryProvider).listDevices();
});

class LicenseState {
  final bool loading;
  final CachedLicense? license;
  final LicenseStatus status;

  const LicenseState({
    this.loading = true,
    this.license,
    this.status = LicenseStatus.none,
  });

  bool get canSell => status.canSell;

  /// Premium (as opposed to the always-on Free plan) — gates the optional
  /// modules in `PremiumGate`, distinct from [canSell] which only gates
  /// finalizing a sale and is `true` for the Free plan too (see
  /// `computeLicenseStatus`'s `LicensePlan.free` special case).
  bool get isPremium =>
      license != null && license!.plan != LicensePlan.free && status.canSell;
}

/// Convenience read of [LicenseState.isPremium], same shape as
/// `isEffectiveOwnerProvider` — the primary thing `PremiumGate` watches.
final isPremiumProvider = Provider<bool>(
  (ref) => ref.watch(licenseControllerProvider).isPremium,
);

/// Flips to `true` once after `LicenseController` auto-downgrades an expired
/// license to the Free plan, so Settings can show a one-time "you're on the
/// Free plan now" notice — same one-shot-notice shape as
/// `pendingAutoGeneratedExpensesProvider` in the recurring-expenses feature.
final pendingPlanDowngradeNoticeProvider = StateProvider<bool>((ref) => false);

final licenseControllerProvider =
    StateNotifierProvider<LicenseController, LicenseState>((ref) {
      return LicenseController(ref)..load();
    });

class LicenseController extends StateNotifier<LicenseState> {
  LicenseController(this._ref) : super(const LicenseState());

  final Ref _ref;
  Timer? _reverifyTimer;

  LicenseRepository get _repo => _ref.read(licenseRepositoryProvider);

  Future<void> load() async {
    final lic = await _repo.current();
    _apply(lic);
    // Pick up admin extensions/revocations without user action: re-verify once
    // at launch and then periodically (best-effort; offline is a no-op).
    if (Env.hasBackend) {
      _silentReverify();
      _reverifyTimer ??= Timer.periodic(
        const Duration(hours: 6),
        (_) => _silentReverify(),
      );
    }
  }

  Future<void> _silentReverify() async {
    if (state.license == null) return;
    try {
      await refreshOnline();
    } catch (_) {
      /* offline / transient — keep cached */
    }
  }

  @override
  void dispose() {
    _reverifyTimer?.cancel();
    super.dispose();
  }

  Future<ActivationResult> activate(String key) async {
    final result = await _repo.activate(key);
    if (result.ok && result.license != null) {
      final promoted = await _promoteFreeShopIfNeeded(result.license!.shopId);
      if (!promoted) {
        await _reopenShopDbIfNeeded(result.license!.shopId);
      }
      _apply(result.license);
    }
    return result;
  }

  /// A Free-plan shop (`shop_id = free-<deviceId>`, purely local — see
  /// `sync_providers.dart`'s `syncEngineProvider`) has no server-side
  /// presence. Activating a key mints a real, server-assigned [toShopId]
  /// distinct from the local one — without this, [_reopenShopDbIfNeeded]
  /// would open a brand-new, empty file at [toShopId] and silently strand
  /// every local sale/product behind the old Free identity. Moves the data
  /// to travel with it instead. Returns true if a promotion ran (which
  /// already reopens the DB at the new shop), so the caller skips its own
  /// plain reopen.
  Future<bool> _promoteFreeShopIfNeeded(String toShopId) async {
    final current = state.license;
    if (current == null ||
        current.plan != LicensePlan.free ||
        current.shopId == toShopId ||
        !AppDatabase.usePerShopDbFiles) {
      return false;
    }
    final fromShopId = current.shopId;
    final settings = _ref.read(settingsRepositoryProvider);
    // Written before the data rewrite starts, cleared only after the file
    // rename succeeds — see `resolvePendingShopPromotion` for how a crash
    // mid-promotion is resumed on next launch.
    await settings.setPendingShopPromotion(fromShopId, toShopId);
    final db = _ref.read(databaseProvider);
    await ShopDataTransitionService(
      db,
    ).promoteShopIdentity(fromShopId: fromShopId, toShopId: toShopId);
    final session = _ref.read(databaseSessionProvider);
    await session?.reopenForShopPromotedFrom(
      fromShopId: fromShopId,
      toShopId: toShopId,
    );
    await settings.clearPendingShopPromotion();
    return true;
  }

  /// Detaches this device's key/trial. Falls back to the Free plan (same
  /// `downgradeToFree` a license lapse already uses) rather than leaving the
  /// device in a bare not-activated state — Sell/Inventory keep working, the
  /// device stays on the shop's own data, and a key can be re-entered later
  /// from the Free-plan section of this screen. Only the defensive
  /// null-license branch (unreachable via the UI — "Remove license" only
  /// ever shows for an active non-free license) still clears to nothing.
  Future<void> deactivate() async {
    final current = state.license;
    if (current == null) {
      await _repo.deactivate();
      _apply(null);
      return;
    }
    final downgraded = await _repo.downgradeToFree(current);
    _apply(downgraded);
  }

  /// Enters the Free plan — no key, no account, no network call. See
  /// `LicenseRepository.startFreePlan`. Currently only reachable from
  /// onboarding (a fresh device with no prior license), but guarded
  /// defensively here in case a future entry point ever calls this on a
  /// device that already has real synced data under a DIFFERENT shop: never
  /// silently mixes data under the new Free shopId. Refuses (returns false)
  /// if there are unsynced writes — same check `BranchRepository.switchBranch`
  /// uses. Legacy shared-DB mode wipes; per-shop mode reopens the Free
  /// shop file and leaves other shops' files intact.
  Future<bool> continueFree() async {
    final current = await _repo.current();
    if (current != null) {
      final db = _ref.read(databaseProvider);
      final pending = await db.select(db.outbox).get();
      if (pending.isNotEmpty) return false;
      if (!AppDatabase.usePerShopDbFiles) {
        await db.wipeSyncedData();
      }
    }
    final lic = await _repo.startFreePlan();
    await _reopenShopDbIfNeeded(lic.shopId);
    _apply(lic);
    return true;
  }

  /// Self-serve, no-account Premium trial — mirrors [activate]'s exact
  /// promote/reopen/apply shape, since both mint a real server shop_id that
  /// may need to inherit this device's local Free-plan data.
  Future<ActivationResult> startFreeTrial(String shopName) async {
    final result = await _repo.startFreeTrial(shopName);
    if (result.ok && result.license != null) {
      final promoted = await _promoteFreeShopIfNeeded(result.license!.shopId);
      if (!promoted) {
        await _reopenShopDbIfNeeded(result.license!.shopId);
      }
      _apply(result.license);
    }
    return result;
  }

  /// Re-checks the license online (same key + device) to pick up an extension
  /// an admin approved after a renewal payment. Reuses `activate`, which
  /// returns the current server-side expiry. No-op offline / with no license.
  Future<ActivationResult> refreshOnline() async {
    final lic = state.license;
    if (lic == null) {
      return const ActivationResult.failure('not_activated');
    }
    // A self-serve trial, the Free plan, or an offline signed token has
    // nothing to re-verify online — there's no real key to look up (a
    // self-serve trial's cached [LicenseRepository.trialKey] is a local
    // placeholder, `LicenseRepository.startFreeTrial`'s own doc comment says
    // so explicitly — calling `activate(LicenseRepository.trialKey)` would
    // just fail server-side every time, as literally no license row has that
    // key). This used to check for a re-typed `'FREE-TRIAL'` literal, a
    // string nothing ever actually sets — dead code that silently defeated
    // the exemption and made every periodic reverify a guaranteed-failing
    // `activate('TRIAL')` call instead. Now both sides share the same
    // constants (defined once on `LicenseRepository`) instead of each file
    // re-typing the literal, so a typo like that can't recur.
    // Since this is also the app's only periodic "is the session still
    // good" heartbeat (`load()` on every launch + every 6h), a trial session
    // still gets a real benefit here: proactively refresh so a JWT that
    // never picked up its `shop_id` claim (e.g. the one-shot refresh right
    // after minting the trial silently failed) has another chance to
    // self-heal, instead of only doing so reactively when some RLS-scoped
    // write already fails.
    if (lic.key == LicenseRepository.trialKey ||
        lic.key == LicenseRepository.freeKey ||
        lic.key.startsWith('MMPOS1.')) {
      // `flutter run --release`'s device stdout isn't relayed to the host
      // terminal on this project's target device, so a temporary debugPrint
      // here was unobservable — replaced with `refreshSessionAndVerifyClaim`,
      // which reports a real failure to Sentry instead (queryable regardless
      // of build mode) and self-heals with a retry, rather than just logging.
      if (lic.key == LicenseRepository.trialKey) {
        await _repo.refreshSessionAndVerifyClaim(lic.shopId);
      }
      return ActivationResult.success(lic);
    }
    final result = await _repo.activate(lic.key);
    if (result.ok) {
      _apply(result.license);
      return result;
    }
    // A pure connectivity failure (not the server telling us the license is
    // actually invalid/mismatched/rate-limited) — fall back to the
    // cryptographic offline token cached alongside the last successful
    // online activation, if one exists and isn't itself expired. Extends
    // coverage past the 7-day online grace window (`GRACE_DAYS` in the
    // `activate` Edge Function) for as long as that cached token remains
    // valid, instead of leaving the shop stuck at whatever the last online
    // status was.
    if (result.errorCode == 'network_error') {
      final fallback = await _tryOfflineFallback(lic);
      if (fallback != null) {
        _apply(fallback);
        return ActivationResult.success(fallback);
      }
    }
    return result;
  }

  /// See [refreshOnline]'s network-failure branch. The I/O half (fetch the
  /// cached token, verify it) lives here; the decision half is
  /// [applyOfflineFallback], kept pure and separately unit-tested.
  Future<CachedLicense?> _tryOfflineFallback(CachedLicense current) async {
    final settings = _ref.read(settingsRepositoryProvider);
    final token = await settings.licenseOfflineFallbackToken(current.shopId);
    if (token == null || token.isEmpty) return null;
    try {
      final deviceId = await settings.deviceId();
      final verified = await OfflineLicense.verify(token, deviceId);
      return applyOfflineFallback(
        current: current,
        verifiedFallback: verified,
        now: DateTime.now(),
      );
    } catch (_) {
      return null;
    }
  }

  /// Applies a [CachedLicense] that was already persisted elsewhere (e.g. by
  /// [LicenseRepository.saveExternal] after a branch switch) — same
  /// shopId-binding + status recompute `activate()`/`load()` already do.
  /// Callers that switch shops must reopen the shop DB *before* this when
  /// [AppDatabase.usePerShopDbFiles] is on (branch/account repos do).
  void applyExternal(CachedLicense lic) => _apply(lic);

  Future<void> _reopenShopDbIfNeeded(String shopId) async {
    if (!AppDatabase.usePerShopDbFiles || shopId.isEmpty) return;
    final session = _ref.read(databaseSessionProvider);
    await session?.reopenForShop(shopId);
  }

  void _apply(CachedLicense? lic) {
    final status = computeLicenseStatus(
      expiresAt: lic?.expiresAt,
      now: DateTime.now(),
      plan: lic?.plan,
      activated: lic != null,
    );
    // Bind the active shop so all data scopes to it.
    if (lic != null) {
      _ref.read(shopIdProvider.notifier).state = lic.shopId;
    }
    state = LicenseState(loading: false, license: lic, status: status);

    // Never leave the shop hard-locked: any lapsed license (an offline key
    // past its grace period, or an online subscription that wasn't renewed)
    // auto-downgrades to the Free plan instead — core POS features keep
    // working, only Premium stays locked until renewal. Fire-and-forget is
    // safe here: worst case this fires again next time `_apply` runs (e.g.
    // the next silent re-verify), which just re-persists the same Free
    // license, a harmless no-op.
    if (lic != null &&
        lic.plan != LicensePlan.free &&
        status.kind == LicenseStatusKind.expired) {
      _repo.downgradeToFree(lic).then((free) {
        // Staleness guard: if a newer `_apply` (e.g. a manual activation
        // that raced ahead of this stale reverify) already replaced
        // `state.license` with something else, applying `free` now would
        // wrongly stomp it and re-pin `shopIdProvider` back to the shop
        // this downgrade was computed for.
        if (!identical(state.license, lic)) return;
        _ref.read(pendingPlanDowngradeNoticeProvider.notifier).state = true;
        _apply(free);
      });
    }
  }
}
