import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';

import '../../core/image_util.dart';
import '../../core/money.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/app_widgets.dart';
import '../../data/local/database.dart';
import '../../l10n/app_localizations.dart';
import '../accounts/payment_account_providers.dart';
import '../analytics/analytics_providers.dart';
import '../license/license_providers.dart';
import '../license/premium_gate.dart';
import 'expense_providers.dart';
import 'expense_repository.dart';
import 'recurring_expense_providers.dart';
import 'recurring_expenses_screen.dart';

String _photoMimeType(String path) {
  final ext = path.split('.').last.toLowerCase();
  return switch (ext) {
    'png' => 'image/png',
    'jpg' || 'jpeg' => 'image/jpeg',
    _ => 'image/jpeg',
  };
}

/// Full-screen view of a receipt photo, with a share/save action so the
/// owner can move a copy off this device (e.g. before switching phones —
/// see the local-only note on the attach button).
class ReceiptPhotoViewer extends StatelessWidget {
  const ReceiptPhotoViewer({super.key, required this.path});
  final String path;

  Future<void> _save(BuildContext context) async {
    await SharePlus.instance.share(
      ShareParams(files: [XFile(path, mimeType: _photoMimeType(path))]),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            tooltip: l.expenseReceiptPhotoSave,
            icon: const Icon(Icons.ios_share),
            onPressed: () => _save(context),
          ),
        ],
      ),
      body: Center(
        child: InteractiveViewer(
          minScale: 0.5,
          maxScale: 4,
          child: Image.file(File(path)),
        ),
      ),
    );
  }
}

IconData categoryIcon(String category) {
  switch (category) {
    case 'rent':
      return Icons.store_outlined;
    case 'utilities':
      return Icons.bolt_outlined;
    case 'wages':
      return Icons.badge_outlined;
    case 'transport':
      return Icons.local_shipping_outlined;
    case 'packaging':
      return Icons.inventory_2_outlined;
    case 'other':
    default:
      return Icons.receipt_long_outlined;
  }
}

String categoryLabel(AppLocalizations l, String category) {
  switch (category) {
    case 'rent':
      return l.expenseCategoryRent;
    case 'utilities':
      return l.expenseCategoryUtilities;
    case 'wages':
      return l.expenseCategoryWages;
    case 'transport':
      return l.expenseCategoryTransport;
    case 'packaging':
      return l.expenseCategoryPackaging;
    case 'other':
    default:
      return l.expenseCategoryOther;
  }
}

/// The shop's non-inventory operating expenses (rent, utilities, wages,
/// transport, packaging). Reached from the Analytics dashboard's "Total
/// expenses" card (where the owner thinks about profit) and from Settings
/// (for discoverability — some owners never open Analytics).
class ExpenseScreen extends ConsumerStatefulWidget {
  const ExpenseScreen({super.key});

  @override
  ConsumerState<ExpenseScreen> createState() => _ExpenseScreenState();
}

class _ExpenseScreenState extends ConsumerState<ExpenseScreen> {
  @override
  void initState() {
    super.initState();
    // The auto-generate check may have already fired (and populated the
    // provider) before this screen was ever opened this session — a plain
    // ref.listen registered at first build would miss that, since it only
    // reacts to changes AFTER registration. Checking the current value on
    // the first frame covers both "just fired" and "fired a while ago."
    WidgetsBinding.instance.addPostFrameCallback((_) => _showAutoGenNotice());
  }

  void _showAutoGenNotice() {
    if (!mounted) return;
    final l = AppLocalizations.of(context);
    final fired = ref.read(pendingAutoGeneratedExpensesProvider);
    if (fired.isEmpty) return;
    ref.read(pendingAutoGeneratedExpensesProvider.notifier).state = const [];
    final names = fired.map((t) => categoryLabel(l, t.category)).join(', ');
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(l.recurringExpenseAutoAdded(fired.length, names))),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    if (ref.watch(licenseControllerProvider).loading || !ref.watch(isPremiumProvider)) {
      return Scaffold(
        appBar: AppBar(title: Text(l.expensesTitle)),
        body: PremiumGate(featureName: l.expensesTitle, child: const SizedBox.shrink()),
      );
    }
    final cur = l.currencySymbol;
    final expenses =
        ref.watch(expensesInRangeProvider).valueOrNull ?? const <Expense>[];
    final total = ref.watch(expensesTotalProvider);
    final range = ref.watch(analyticsRangeProvider);
    final df = DateFormat('yyyy-MM-dd');

    return Scaffold(
      appBar: AppBar(
        title: Text(l.expensesTitle),
        actions: [
          IconButton(
            tooltip: l.recurringExpenseAddFromTemplate,
            icon: const Icon(Icons.playlist_add),
            onPressed: () => _openTemplatePicker(context),
          ),
          IconButton(
            tooltip: l.recurringExpenseManage,
            icon: const Icon(Icons.repeat),
            onPressed: () => Navigator.of(context).push(MaterialPageRoute(
              builder: (_) => const RecurringExpensesScreen(),
            )),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _openDialog(context),
        child: const Icon(Icons.add),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(AppTheme.space3),
            child: SegmentedButton<AnalyticsRange>(
              segments: [
                ButtonSegment(
                    value: AnalyticsRange.today,
                    label: Text(l.analyticsRangeToday)),
                ButtonSegment(
                    value: AnalyticsRange.week,
                    label: Text(l.analyticsRangeWeek)),
                ButtonSegment(
                    value: AnalyticsRange.month,
                    label: Text(l.analyticsRangeMonth)),
              ],
              selected: {range},
              onSelectionChanged: (s) =>
                  ref.read(analyticsRangeProvider.notifier).state = s.first,
            ),
          ),
          Container(
            width: double.infinity,
            color: Theme.of(context).colorScheme.surfaceContainerHighest,
            padding: const EdgeInsets.all(AppTheme.space4),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(l.expensesTotal,
                    style: Theme.of(context).textTheme.labelMedium),
                const SizedBox(height: AppTheme.space1),
                MoneyText(
                  Money(total).withSymbol(cur),
                  textAlign: TextAlign.left,
                  emphasis: true,
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
              ],
            ),
          ),
          Expanded(
            child: expenses.isEmpty
                ? EmptyStateView(
                    icon: Icons.receipt_long_outlined,
                    title: l.expensesEmpty,
                  )
                : ListView.separated(
                    itemCount: expenses.length,
                    separatorBuilder: (_, _) => const Divider(height: 1),
                    itemBuilder: (_, i) {
                      final e = expenses[i];
                      return ListTile(
                        leading: IconAvatar(icon: categoryIcon(e.category)),
                        title: Text(categoryLabel(l, e.category)),
                        subtitle: Text(
                          e.note == null || e.note!.isEmpty
                              ? df.format(e.date)
                              : '${df.format(e.date)} · ${e.note}',
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                        trailing: MoneyText(
                          Money(e.amount).withSymbol(cur),
                          emphasis: true,
                        ),
                        onTap: () => _openDialog(context, existing: e),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }

  Future<void> _openDialog(BuildContext context,
      {Expense? existing, ExpenseTemplatePrefill? prefill}) {
    return showDialog<void>(
      context: context,
      builder: (_) => _ExpenseDialog(existing: existing, prefill: prefill),
    );
  }

  Future<void> _openTemplatePicker(BuildContext context) async {
    final l = AppLocalizations.of(context);
    final templates = await ref.read(recurringExpenseTemplatesProvider.future);
    final active = templates.where((t) => t.active).toList();
    if (!context.mounted) return;
    if (active.isEmpty) {
      Navigator.of(context).push(MaterialPageRoute(
        builder: (_) => const RecurringExpensesScreen(),
      ));
      return;
    }
    final picked = await showModalBottomSheet<RecurringExpense>(
      context: context,
      builder: (ctx) => SafeArea(
        child: ListView(
          shrinkWrap: true,
          children: [
            Padding(
              padding: const EdgeInsets.all(AppTheme.space3),
              child: Text(l.recurringExpenseAddFromTemplate,
                  style: Theme.of(ctx).textTheme.titleMedium),
            ),
            for (final t in active)
              ListTile(
                leading: Icon(categoryIcon(t.category)),
                title: Text(categoryLabel(l, t.category)),
                subtitle: t.note == null || t.note!.isEmpty
                    ? null
                    : Text(t.note!, maxLines: 1, overflow: TextOverflow.ellipsis),
                trailing: Text(Money(t.amount).withSymbol(l.currencySymbol),
                    style: const TextStyle(fontWeight: FontWeight.bold)),
                onTap: () => Navigator.pop(ctx, t),
              ),
          ],
        ),
      ),
    );
    if (picked == null || !context.mounted) return;
    await _openDialog(context,
        prefill: ExpenseTemplatePrefill(
            category: picked.category, amount: picked.amount, note: picked.note));
  }
}

/// Prefill values from a recurring-expense template — deliberately not the
/// `RecurringExpense` row itself, so this dialog doesn't need to know
/// anything about that table.
class ExpenseTemplatePrefill {
  const ExpenseTemplatePrefill(
      {required this.category, required this.amount, this.note});
  final String category;
  final int amount;
  final String? note;
}

class _ExpenseDialog extends ConsumerStatefulWidget {
  const _ExpenseDialog({this.existing, this.prefill});
  final Expense? existing;
  final ExpenseTemplatePrefill? prefill;

  @override
  ConsumerState<_ExpenseDialog> createState() => _ExpenseDialogState();
}

class _ExpenseDialogState extends ConsumerState<_ExpenseDialog> {
  final _amount = TextEditingController();
  final _note = TextEditingController();
  late String _category;
  late DateTime _date;
  String? _receiptPhotoPath;
  String? _accountId;
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    final e = widget.existing;
    final p = widget.prefill;
    _category = e?.category ?? p?.category ?? expenseCategories.first;
    _date = e?.date ?? DateTime.now();
    _receiptPhotoPath = e?.receiptPhotoPath;
    _accountId = e?.accountId;
    if (e != null) {
      _amount.text = '${e.amount}';
      _note.text = e.note ?? '';
    } else if (p != null) {
      _amount.text = '${p.amount}';
      _note.text = p.note ?? '';
    }
  }

  @override
  void dispose() {
    _amount.dispose();
    _note.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _date,
      firstDate: DateTime(2020),
      lastDate: DateTime.now().add(const Duration(days: 1)),
    );
    if (picked != null) setState(() => _date = picked);
  }

  Future<void> _pickReceiptPhoto() async {
    final res =
        await FilePicker.platform.pickFiles(type: FileType.image, withData: true);
    final file = res?.files.firstOrNull;
    if (file == null || file.bytes == null) return;
    final c = compressImage(Uint8List.fromList(file.bytes!),
        fallbackExt: (file.extension ?? 'jpg').toLowerCase());
    final path = await ref
        .read(expenseRepositoryProvider)
        .saveReceiptPhoto(c.bytes, ext: c.ext);
    if (mounted) setState(() => _receiptPhotoPath = path);
  }

  Future<void> _save() async {
    final l = AppLocalizations.of(context);
    final amount = int.tryParse(_amount.text.trim()) ?? 0;
    if (amount <= 0) return;
    final messenger = ScaffoldMessenger.of(context);
    final navigator = Navigator.of(context);
    setState(() => _saving = true);
    try {
      await ref.read(expenseRepositoryProvider).upsertExpense(
            id: widget.existing?.id,
            category: _category,
            amount: amount,
            date: _date,
            note: _note.text.trim().isEmpty ? null : _note.text.trim(),
            receiptPhotoPath: _receiptPhotoPath,
            accountId: _accountId,
          );
      navigator.pop();
      messenger.showSnackBar(SnackBar(content: Text(l.expenseSaved)));
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  Future<void> _delete() async {
    final l = AppLocalizations.of(context);
    final messenger = ScaffoldMessenger.of(context);
    final navigator = Navigator.of(context);
    final confirmed = await showDialog<bool>(
      context: context,
      // Pop via the dialog's own context — showDialog defaults to the root
      // navigator while this screen's own context belongs to go_router's
      // nested shell-branch navigator; popping via the outer context pops
      // the wrong navigator.
      builder: (dialogContext) => AlertDialog(
        title: Text(l.expenseDeleteConfirmTitle),
        content: Text(l.expenseDeleteConfirmBody),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: Text(l.commonCancel),
          ),
          FilledButton(
            style: AppTheme.dangerFilledButtonStyle(dialogContext),
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: Text(l.commonDelete),
          ),
        ],
      ),
    );
    if (confirmed != true) return;
    await ref.read(expenseRepositoryProvider).deleteExpense(widget.existing!.id);
    navigator.pop();
    messenger.showSnackBar(SnackBar(content: Text(l.expenseDeleted)));
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    final df = DateFormat('yyyy-MM-dd');
    final photoExists =
        _receiptPhotoPath != null && File(_receiptPhotoPath!).existsSync();

    return AlertDialog(
      title: Text(widget.existing == null ? l.expenseAdd : l.expenseEdit),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TextField(
              controller: _amount,
              autofocus: widget.existing == null,
              keyboardType: TextInputType.number,
              inputFormatters: [FilteringTextInputFormatter.digitsOnly],
              decoration: InputDecoration(labelText: l.expenseAmount),
            ),
            const SizedBox(height: AppTheme.space3),
            Wrap(
              spacing: AppTheme.space2,
              runSpacing: AppTheme.space2,
              children: [
                for (final c in expenseCategories)
                  ChoiceChip(
                    label: Text(categoryLabel(l, c)),
                    selected: _category == c,
                    onSelected: (_) => setState(() => _category = c),
                  ),
              ],
            ),
            const SizedBox(height: AppTheme.space3),
            Text(l.expensePaidFrom, style: Theme.of(context).textTheme.labelLarge),
            const SizedBox(height: AppTheme.space1),
            Wrap(
              spacing: AppTheme.space2,
              runSpacing: AppTheme.space2,
              children: [
                ChoiceChip(
                  label: Text(l.paymentCash),
                  selected: _accountId == null,
                  onSelected: (_) => setState(() => _accountId = null),
                ),
                for (final a in ref.watch(paymentAccountsProvider).valueOrNull ?? const [])
                  ChoiceChip(
                    label: Text(a.name),
                    selected: _accountId == a.id,
                    onSelected: (_) => setState(() => _accountId = a.id),
                  ),
              ],
            ),
            const SizedBox(height: AppTheme.space3),
            OutlinedButton.icon(
              onPressed: _pickDate,
              icon: const Icon(Icons.calendar_today_outlined, size: 18),
              label: Text(df.format(_date)),
            ),
            const SizedBox(height: AppTheme.space3),
            TextField(
              controller: _note,
              decoration: InputDecoration(labelText: l.expenseNote),
            ),
            const SizedBox(height: AppTheme.space3),
            if (photoExists) ...[
              Row(
                children: [
                  InkWell(
                    borderRadius: BorderRadius.circular(8),
                    onTap: () => Navigator.of(context).push(MaterialPageRoute(
                        builder: (_) =>
                            ReceiptPhotoViewer(path: _receiptPhotoPath!))),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(8),
                      child: Image.file(
                        File(_receiptPhotoPath!),
                        width: 72,
                        height: 72,
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                  const SizedBox(width: AppTheme.space3),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        TextButton(
                          onPressed: () => Navigator.of(context).push(
                              MaterialPageRoute(
                                  builder: (_) => ReceiptPhotoViewer(
                                      path: _receiptPhotoPath!))),
                          style: TextButton.styleFrom(
                              padding: EdgeInsets.zero,
                              minimumSize: const Size(0, 0),
                              tapTargetSize:
                                  MaterialTapTargetSize.shrinkWrap,
                              alignment: Alignment.centerLeft),
                          child: Text(l.expenseReceiptPhotoView),
                        ),
                        TextButton(
                          onPressed: _pickReceiptPhoto,
                          style: TextButton.styleFrom(
                              padding: EdgeInsets.zero,
                              minimumSize: const Size(0, 0),
                              tapTargetSize:
                                  MaterialTapTargetSize.shrinkWrap,
                              alignment: Alignment.centerLeft),
                          child: Text(l.expenseReceiptPhotoReplace),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ] else
              OutlinedButton.icon(
                onPressed: _pickReceiptPhoto,
                icon: const Icon(Icons.camera_alt_outlined, size: 18),
                label: Text(l.expenseReceiptPhotoAdd),
              ),
            if (_receiptPhotoPath != null && !photoExists)
              Padding(
                padding: const EdgeInsets.only(top: AppTheme.space1),
                child: Text(l.expenseReceiptPhotoMissing,
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: AppColors.of(context).danger)),
              ),
            Padding(
              padding: const EdgeInsets.only(top: AppTheme.space1),
              child: Text(l.expenseReceiptPhotoHint,
                  style: Theme.of(context).textTheme.bodySmall),
            ),
          ],
        ),
      ),
      actions: [
        if (widget.existing != null)
          TextButton(
            onPressed: _saving ? null : _delete,
            style: TextButton.styleFrom(
                foregroundColor: AppColors.of(context).danger),
            child: Text(l.commonDelete),
          ),
        TextButton(
          onPressed: _saving ? null : () => Navigator.of(context).pop(),
          child: Text(l.commonCancel),
        ),
        FilledButton(
          onPressed: _saving ? null : _save,
          child: Text(l.commonSave),
        ),
      ],
    );
  }
}
