import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../license/license_providers.dart';
import 'recurring_expense_providers.dart';

/// Runs `RecurringExpenseRepository.generateDueExpenses()` once per app
/// open (not a timer/poll — this is 100% local, no network round-trip to
/// race) and stashes the result in `pendingAutoGeneratedExpensesProvider`
/// for the Expenses screen to show as a one-time notice. Same
/// once-at-launch shape as `ReferralWatcher`, minus the polling/lifecycle
/// hooks that one needs for its remote check.
class RecurringExpenseGenerator {
  RecurringExpenseGenerator(this._ref) {
    // Deferred so shopIdProvider has settled after LicenseController.load()
    // — same reasoning as ReferralWatcher's startup deferral.
    _timer = Timer(const Duration(seconds: 3), _run);
  }

  final Ref _ref;
  Timer? _timer;

  Future<void> _run() async {
    try {
      if (_ref.read(licenseControllerProvider).license == null) return;
      final fired = await _ref
          .read(recurringExpenseRepositoryProvider)
          .generateDueExpenses();
      if (fired.isNotEmpty) {
        _ref.read(pendingAutoGeneratedExpensesProvider.notifier).state = fired;
      }
    } catch (_) {
      // Offline / transient local-DB issue — just skip this launch, the
      // next app open tries again.
    }
  }

  void dispose() {
    _timer?.cancel();
  }
}
