import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/providers.dart';
import '../../data/local/database.dart';
import 'expense_providers.dart';
import 'recurring_expense_generator.dart';
import 'recurring_expense_repository.dart';

final recurringExpenseRepositoryProvider =
    Provider<RecurringExpenseRepository>((ref) {
  return RecurringExpenseRepository(
    ref.watch(databaseProvider),
    ref.watch(shopIdProvider),
    ref.watch(expenseRepositoryProvider),
  );
});

final recurringExpenseTemplatesProvider =
    StreamProvider<List<RecurringExpense>>((ref) {
  return ref.watch(recurringExpenseRepositoryProvider).watchTemplates();
});

/// Templates `RecurringExpenseGenerator` just auto-generated an `Expense`
/// for, waiting to be shown as a one-time notice the next time the
/// Expenses screen opens. Empty most of the time.
final pendingAutoGeneratedExpensesProvider =
    StateProvider<List<RecurringExpense>>((ref) => const []);

/// Kept alive for the app's lifetime (watched in `app.dart`, same pattern
/// as `storefrontOrderWatcherProvider`) — runs `generateDueExpenses()` once per
/// cold start.
final recurringExpenseGeneratorProvider =
    Provider<RecurringExpenseGenerator>((ref) {
  final generator = RecurringExpenseGenerator(ref);
  ref.onDispose(generator.dispose);
  return generator;
});
